apiVersion: appo11y.grafana.com/v1alpha1
kind: Instrumenter
metadata:
  labels:
    app.kubernetes.io/name: instrumenter
    app.kubernetes.io/instance: instrumenter-sample
    app.kubernetes.io/part-of: ebpf-autoinstrument-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ebpf-autoinstrument-operator
  name: instrumenter-sample
spec:
  # TODO(user): Add fields here
